name: Redirect
version: 2.0.0
description: Simple redirect plugin for Flextype.
author:
  name: Sergey Romanenko
  email: sergey.romaneko@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/redirect
bugs: https://github.com/flextype-plugins/redirect/issues
license: MIT
